// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6sg6CAdcDtsgZD8iDWfv5yKmXZdkLZQ',
    appId: '1:798282077661:web:79f0a6b3ff579dc9341234',
    messagingSenderId: '798282077661',
    projectId: 'eduprova-app',
    authDomain: 'eduprova-app.firebaseapp.com',
    storageBucket: 'eduprova-app.firebasestorage.app',
    iosClientId:
        '798282077661-2sl2th5g4eoo8e6vgokomksvjji7l9lc.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvFcXeVPF60vjMju2U0DLLk0MQEIVoq4',
    appId: '1:798282077661:android:29c7315d387ef0fe341234',
    messagingSenderId: '798282077661',
    projectId: 'eduprova-app',
    storageBucket: 'eduprova-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFL_-lDR_wbiZadEQhkjCviVqt4TRaISY',
    appId: '1:798282077661:ios:a6920b5a2dd5efe2341234',
    messagingSenderId: '798282077661',
    projectId: 'eduprova-app',
    storageBucket: 'eduprova-app.firebasestorage.app',
    iosClientId:
        '798282077661-pti1ko108t58pnfhokcpd5j2o32uk574.apps.googleusercontent.com',
    iosBundleId: 'com.dilshaj.infotech.eduprova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFL_-lDR_wbiZadEQhkjCviVqt4TRaISY',
    appId: '1:798282077661:ios:a6920b5a2dd5efe2341234',
    messagingSenderId: '798282077661',
    projectId: 'eduprova-app',
    storageBucket: 'eduprova-app.firebasestorage.app',
    iosClientId:
        '798282077661-pti1ko108t58pnfhokcpd5j2o32uk574.apps.googleusercontent.com',
    iosBundleId: 'com.dilshaj.infotech.eduprova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ6sg6CAdcDtsgZD8iDWfv5yKmXZdkLZQ',
    appId: '1:798282077661:web:c4099b601cb971ce341234',
    messagingSenderId: '798282077661',
    projectId: 'eduprova-app',
    authDomain: 'eduprova-app.firebaseapp.com',
    storageBucket: 'eduprova-app.firebasestorage.app',
    iosClientId:
        '798282077661-2sl2th5g4eoo8e6vgokomksvjji7l9lc.apps.googleusercontent.com',
  );
}
